In [ ]:
# Import needed libraries
import numpy as np

#### Task 1: **Знайти в датасеті таргет та видалити цю колонку з датасету (видаляти за індексом)**

In [ ]:
# Load the dataset without last column using parameter 'usecols='
data_iris = np.genfromtxt('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', dtype=float, delimiter=',', usecols=(0,1,2,3))

In [ ]:
# Check the dataset shape
print(f'The dataset shape: rows = {data_iris.shape[0]}, columns = {data_iris.shape[1]}')

The dataset shape: rows = 150, columns = 4


In [ ]:
data_iris[0:2]    # Print first two rows

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2]])

#### Task 2: **Перетворити колонки, що залишились в 2D масив (або впевнитись, що це уже 2D масив)**

In [ ]:
print(f'Розмірність масиву = {data_iris.ndim}')

Розмірність масиву = 2


#### Task 3: **Порахувати mean, median, standard deviation для 1-ї колонки**

In [ ]:
print("Mean of the 1-st column is: ", np.mean(data_iris[:, 0]))

Mean of the 1-st column is:  5.843333333333334


In [ ]:
print("Median of the 1-st column is: ", np.median(data_iris[:, 0]))

Median of the 1-st column is:  5.8


In [ ]:
print("Standard deviation of the 1-st column is: ", np.std(data_iris[:, 0]))

Standard deviation of the 1-st column is:  0.8253012917851409


#### Task 4: **Вставити 20 значень np.nan на випадкові позиції в масиві (при використанні звичайного рандому можуть накластись позиції, тому знайти рішення, яке гарантує 20 унікальних позицій)**

In [ ]:
num = 20  # Number of NaN to be inserted into the array
# data_iris.ravel()[np.random.choice(data_iris.size, num, replace=False)] = np.nan

In [ ]:
# Choose random indexes where NaN values will be inserted
idx_nan = np.random.choice(data_iris.size, num, replace=False)
print(np.sort(idx_nan), "\n", "Total number of choosen indices:", len(idx_nan))

[ 38  61  71 138 148 153 233 269 285 292 357 379 413 414 421 453 485 489
 518 537] 
 Total number of choosen indices: 20


In [ ]:
# Add NaN values to the array
data_iris.ravel()[idx_nan] = np.nan
# Print first 10 rows to check whether the NaN values
# have been inserted
print(data_iris[:10])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 nan 0.1]]


#### Task 5: **Знайти позиції вставлених значень np.nan в 1-й колонці**

In [ ]:
# Find indices of nan values in the first column
idxs_nan_first_column = np.argwhere(np.isnan(data_iris[:, 0]))
print(f"Here are indices of nan values in the first column of the array:\n {idxs_nan_first_column}")

Here are indices of nan values in the first column of the array:
 [[37]
 [73]]


#### Task 6: **Відфільтрувати массив за умовою: значення в 3-й колонці > 1.5 та значения в 1-й колонці < 5.0 (зберегти у іншу змінну)**

In [ ]:
filter = (data_iris[:, 2] > 1.5) & (data_iris[:, 0] < 5.0)
data_iris_filtered = data_iris[filter]
print(f"Filtered array with shape {data_iris_filtered.shape}:\n {data_iris_filtered}")

Filtered array with shape (6, 4):
 [[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


#### Task 7: **Замінити всі значення np.nan на 0**

In [ ]:
all_nan = np.isnan(data_iris)
data_iris[all_nan] = 0
data_iris[:5, :]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

#### Task 8: **Порахувати всі унікальні значення в массиві та вивести їх разом із кількістю**

In [ ]:
uniqs, counts = np.unique(data_iris, return_counts=True)
for i in range(len(uniqs)):
  print(f"There are {counts[i]} following unique values: {uniqs[i]}")

There are 20 following unique values: 0.0
There are 6 following unique values: 0.1
There are 28 following unique values: 0.2
There are 6 following unique values: 0.3
There are 7 following unique values: 0.4
There are 1 following unique values: 0.5
There are 1 following unique values: 0.6
There are 8 following unique values: 1.0
There are 4 following unique values: 1.1
There are 7 following unique values: 1.2
There are 19 following unique values: 1.3
There are 20 following unique values: 1.4
There are 24 following unique values: 1.5
There are 11 following unique values: 1.6
There are 6 following unique values: 1.7
There are 12 following unique values: 1.8
There are 7 following unique values: 1.9
There are 7 following unique values: 2.0
There are 6 following unique values: 2.1
There are 6 following unique values: 2.2
There are 12 following unique values: 2.3
There are 6 following unique values: 2.4
There are 9 following unique values: 2.5
There are 4 following unique values: 2.6
There ar

#### Task 9: **Розбити масив по вертикалі на 2 рівні частини (не використовувати абсолютні числа, мають бути два массиви по 4 колонки)**

In [ ]:
data_iris_1, data_iris_2 = np.vsplit(data_iris, 2)
print(f"After spliting we have first new array with shape: {data_iris_1.shape},\nand second new array with shape: {data_iris_2.shape}")

After spliting we have first new array with shape: (75, 4),
and second new array with shape: (75, 4)


#### Task 10: **Відсортувати обидва массиви по 1-й колонці: 1-й за збільшенням, 2-й за зменшенням**

In [ ]:
data_iris_1_sorted = data_iris_1[data_iris_1[:, 0].argsort()]
data_iris_2_sorted = data_iris_2[data_iris_2[:, 0].argsort()[::-1]]
print(f"Sorted first array (view of a part of it) by first column ascending:\n {data_iris_1_sorted[:7, :]}")
print(f"Sorted second array (view of a part of it) by first column descending:\n {data_iris_2_sorted[:7, :]}")

Sorted first array (view of a part of it) by first column ascending:
 [[0.  3.1 1.5 0.1]
 [0.  2.8 4.7 1.2]
 [4.3 3.  1.1 0.1]
 [4.4 3.2 1.3 0.2]
 [4.4 0.  1.3 0.2]
 [4.4 2.9 1.4 0.2]
 [4.5 2.3 1.3 0.3]]
Sorted second array (view of a part of it) by first column descending:
 [[7.9 3.8 6.4 2. ]
 [7.7 0.  6.7 2. ]
 [7.7 2.6 6.9 2.3]
 [7.7 3.8 6.7 2.2]
 [7.7 3.  6.1 2.3]
 [7.6 0.  6.6 2.1]
 [7.4 2.8 6.1 1.9]]


#### Task 11: **Зібрати обидва массиви в одне ціле**

In [ ]:
data_iris_sorted = np.vstack((data_iris_1_sorted, data_iris_2_sorted))

#### Task 12: **Знайти найбільш часто повторюване значення в массиві**

In [ ]:
# Search for unique values and their counts in the array
uniqs, counts = np.unique(data_iris_sorted, return_counts=True)
max_counts_idx = np.argmax(counts)
most_freq_value = uniqs[max_counts_idx]
print(f"Most frequent value in the array is: {most_freq_value},\n\
it is repeatead {counts[max_counts_idx]} times")

Most frequent value in the array is: 0.2,
it is repeatead 28 times


#### Task 13: **Написати функцію, яка б множила всі значення в колонці, які менше середнього значения в цій колонці, на 2, і ділила інші значення на 4.**

In [ ]:
def calculator(vector: np.ndarray, mean: float) -> np.ndarray:
  '''
  Function accepts numpy.ndarray, provides calculation
  on its values with certain conditions and
  returns numpy.ndarray with results
  '''
  if vector < mean:
    return vector * 2
  else:
    return vector / 4

#### Task 14: **Застосувати отриману функцію до 3-ї колонки**

In [ ]:
# Calculate mean of 3-rd column
mean = data_iris_sorted[:, 2].mean()

# Vectorize the function with the purpose to apply it
# to vectors.
calculator_vector = np.vectorize(calculator, otypes=[float])

# Apply the function to the 3-rd column of the array in place
data_iris_sorted[:, 2] = calculator_vector(data_iris_sorted[:, 2], mean)
data_iris_sorted[:10, :]    # Check whether the 3-rd column values have been changed

array([[0.   , 3.1  , 3.   , 0.1  ],
       [0.   , 2.8  , 1.175, 1.2  ],
       [4.3  , 3.   , 2.2  , 0.1  ],
       [4.4  , 3.2  , 2.6  , 0.2  ],
       [4.4  , 0.   , 2.6  , 0.2  ],
       [4.4  , 2.9  , 2.8  , 0.2  ],
       [4.5  , 2.3  , 2.6  , 0.3  ],
       [4.6  , 3.4  , 2.8  , 0.3  ],
       [4.6  , 3.1  , 3.   , 0.2  ],
       [4.6  , 3.6  , 2.   , 0.2  ]])

### **End of Notebook**